### ISSUE TITLE
Update helm chart to support mutual TLS

### ISSUE THREAD

**Issue by marcelloromani** [splunk/fabric-logger#20]
In #19 the application supports mutual TLS via two new env vars.

The helm chart hasn't been updated to add support for them.

**Comment by marcelloromani** [comment]
I've tried deploying the branch in the PR, but when I try to activate logging for a channel I get internal server error

```
root@fabric-logger-peer0-7b46fffc86-t5fcj:/usr/src/app# curl http://localhost:8080/channels/mychannel
Internal Server Error
```

If I perform the same deployment with the code from `master`, the `curl` call is successful. I get a "bad certificate" from the client, but that's expected because master doesn't support mutual TLS.

I suspect there's something wrong with the code in release-1.1.1, wichi is used is the PR.

**Comment by dexa187** [comment]
@marcelloromani are you using the auto create secrets  "create: true"  in the values.yaml  https://github.com/splunk/fabric-logger/blob/rmoore/clientcerthelm/helm-chart/fabric-logger/values.yaml#L22  or setting the secrets individually?

**Comment by marcelloromani** [comment]
@dexa187 I'm not using the "create secrets" setting, I'm setting the secrets individually.

**Comment by marcelloromani** [comment]
Found the issue.

The Internal server error was due to a certificate validation failure.

More details here https://github.com/splunk/fabric-logger/issues/27
