### ISSUE TITLE
tls client cert/key read server.crt/server.key

### ISSUE THREAD

**Issue by marcelloromani** [splunk/fabric-logger#26]
In `fabric-logger/helm-chart/fabric-logger/templates/secret.yaml` we have:

```
  clientCert.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/tls/server.crt" .Values.peer.orgDomain .Values.peer.peerName .Values.peer.orgDomain ) | b64enc }}
  clientKey.pem: |-
      {{ $.Files.Get (printf "crypto-config/peerOrganizations/%s/peers/%s.%s/tls/server.key" .Values.peer.orgDomain .Values.peer.peerName .Values.peer.orgDomain ) | b64enc }}
```

I'm wondering if `server.crt` and  `server.key` shouldn't be instead `client.crt` and  `client.key`

Reference: https://github.com/splunk/fabric-logger/blob/rmoore/clientcerthelm/helm-chart/fabric-logger/templates/secret.yaml#L20

**Comment by dexa187** [comment]
The reason this is set to server.crt and key is based on the way that defaults are setup in fabric
[https://hyperledger-fabric.readthedocs.io/en/release-2.0/enable_tls.html](url)
> By default, a peer node will use the same certificate and private key pair when acting as a TLS server and client. To use a different certificate and private key pair for the client side, set the peer.tls.clientCert.file and peer.tls.clientKey.file configuration properties to the fully qualified path of the client certificate and key file, respectively.

**Comment by marcelloromani** [comment]
Thanks for the explanation.
