### ISSUE TITLE
fabric-logger not handling hidden characters in config file

### ISSUE THREAD

**Issue by Moogz** [splunk/fabric-logger#37]

**Comment by dexa187** [comment]
https://github.com/splunk/fabric-logger/tree/rmoore/bug-37

Waiting on validation from customer.

**Comment by dexa187** [comment]
This issue turned out to be hidden chars in the config for splunk url.  Will add parsing to verify the url is well formed.

**Comment by dexa187** [comment]
Fixed in #45
