### ISSUE TITLE
Prometheus Metrics Support

### ISSUE THREAD

**Issue by dexa187** [splunk/fabric-logger#43]
Current statsd metrics are not ideal as fabric requires a restart if the Splunk destination changes.  Add support to scrape the prometheus metrics from orderers, peer and send them to splunk via hec as splunk does not currently have a native prometheus scraping solution.
This probably should be implemented as a shared library for use with other projects.

**Comment by ccordi** [comment]
This was added in https://github.com/splunk/fabric-logger/pull/69.
