### ISSUE TITLE
ghcr.io/splunkdlt/fabric-logger:release-1.2.1 doesn't exist 

### ISSUE THREAD

**Issue by esumit** [splunk/fabric-logger#86]
@j4ys0n 
ghcr.io/splunkdlt/fabric-logger:release-1.2.1 doesn't exist -> refer to line 65 : 
https://github.com/splunk/fabric-logger/blob/10321fd84b800249bf66e6dd2ced01130b6866d6/examples/vaccine-demo/docker-compose-splunk.yaml#L65 

release-1.2.1 doesn't exist https://github.com/orgs/splunkdlt/packages/container/package/fabric-logger

So error returned while running ./start.sh 

Pulling fabric-logger.example.com (ghcr.io/splunkdlt/fabric-logger:release-1.2.1)...
**ERROR: name unknown**

**Comment by j4ys0n** [comment]
good catch.

i'll push the fix in the morning, but you can change it to this and it should work:
```
ghcr.io/splunkdlt/fabric-logger:1.2.1 
```

**Comment by esumit** [comment]
Thanks @j4ys0n , I will try this ghcr.io/splunkdlt/fabric-logger:1.2.1  then :-)
